CREATE TABLE `artesao`.`users` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `USERNAME` VARCHAR(50) NOT NULL, 
    `EMAIL` VARCHAR(100) NOT NULL, 
    `NAME` VARCHAR(50) NOT NULL, 
    `AVATAR` VARCHAR(255) NOT NULL, 
    `CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    `UPDATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (`ID`)
    );