CREATE TABLE `artesao`.`comments` (
    `ID` INT NOT NULL AUTO_INCREMENT, 
    `CUSTOMER` VARCHAR(50) NOT NULL, 
    `CUSTOMER_ID` INT NOT NULL, 
    `ARTWORK` VARCHAR(50) NOT NULL, 
    `ARTWORK_ID` INT NOT NULL, 
    `CONTENT` TEXT NOT NULL, 
    `CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    `UPDATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (`ID`)
    FOREIGN KEY (CUSTOMER_ID) REFERENCES customers(ID)
    FOREIGN KEY (ARTWORK_ID) REFERENCES artworks(ID)
    );
