CREATE TABLE `artesao`.`customers` (
    `ID` INT NOT NULL AUTO_INCREMENT, 
    `FIRST_NAME` VARCHAR(50) NOT NULL, 
    `LAST_NAME` VARCHAR(50) NOT NULL, 
    `USER` VARCHAR(20) NOT NULL, 
    'USER_ID' INT NOT NULL,
    `ROLE` VARCHAR(20) NOT NULL, 
    `FIELD` VARCHAR(20) NOT NULL, 
    `WHATSAPP` VARCHAR(20) NOT NULL, 
    `STATUS` BOOLEAN NOT NULL,
    `CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    `UPDATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (`ID`)
    FOREIGN KEY (USER_ID) REFERENCES users(ID)
    );