-- ::Up
CREATE TABLE `profiles` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `USER_ID` INT NOT NULL,
    `NAME` VARCHAR(50) NOT NULL,
    `AVATAR` VARCHAR(255) NOT NULL,
    `CREATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    `UPDATED` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    PRIMARY KEY (`ID`)
);

-- ::Down
DROP TABLE `profiles`;